### PR TITLE
Make GET /api/emotes/:shortcode public

### PR DESCRIPTION
**Pull request by bates64**
Paving the way for client-side global emotes (`:woah+server.com:` or similar)!

image

### CODE REVIEW

**Comment by bates64** [comment]
We should get this implemented in `@decent/server` ASAP so we don't end up having weird feature disparity between spec and server.

**Review by towerofnix — COMMENTED** [review]
This looks good to me, but I wonder if it's necessary to be specifically specified, at least in the list of `+ (...)` things? We don't have the old authorization system anymore, which means it doesn't really make sense to specify "public" endpoints -- all endpoints are inherently public, after all. (That is, if it's not specified that an endpoint requires a session, it doesn't.) Would it make more sense to instead have this as a "Note:" below the "302 redirects to..." paragraph?

**Comment by towerofnix** [comment]
>We should get this implemented in `@decent/server` ASAP so we don't end up having weird feature disparity between spec and server.

There's no such thing as "private" endpoints (as I explained above) so.. does this actually require any changes in `@decent/server`? (The `/emotes/:shortcode` endpoint [doesn't do any session checking itself](https://github.com/decent-chat/decent/blob/114da7764e1270d731d9a23ddd08c2487541b0b0/packages/server/api.js#L328-L340).)

**Comment by bates64** [comment]
Hm, I guess you're right! I reread the Authentication section and, yeah, only endpoints expecting permissions expect session IDs - this PR is redundant, then.

Closing.

**Pull request closed without merging**
